//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMarket.ForDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Genre { get; set; }
        public string Author { get; set; }
        public int CountInMarket { get; set; }
        public int CountInStock { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public int Cost { get; set; }
    }
}
